### ISSUE TITLE
Gradle version issue

### ISSUE THREAD

**Issue by deep1931** [mattermoran/map_launcher#128] opened 2022-09-19 12:08 UTC
Hello 

Facing an issue on compile time

```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':map_launcher' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

Please provide solution, thanks.

**Comment by mattermoran** [comment] 2022-09-19 12:29
I just bumped kotlin version 1.5.31 and released on pub as v2.4.0. Give it a try and let me know if it works :)

**Comment by mattermoran** [comment] 2022-09-24 05:11
Closing as duplicate of https://github.com/mattermoran/map_launcher/issues/118

**Closed by mattermoran** 2022-09-24 05:11 UTC
