### ISSUE TITLE
MapLauncher.installedMaps returns empty list

### ISSUE THREAD

**Issue by BasPhair** [mattermoran/map_launcher#58] opened 2021-01-27 18:25 UTC
MapLauncher.installedMaps returns an empty list. This occurs on my Pixel 2 that has google maps, and several other map_launcher supported maps. I have attempted running flutter clean, but the problem persists.

Additionally, I can get the desired behavior with the [url_launcher](https://pub.dev/packages/url_launcher) launch function and constructing URL requests [per here](https://developers.google.com/maps/documentation/urls/get-started#directions-action).

**Comment by mattermoran** [comment] 2021-01-28 00:07
That's very strange. That could possibly happen on ios if url scheme are not added to info.plist but android generally does not have that issue. 

Is there any output in the console?

I would also need a flutter doctor output

**Comment by BasPhair** [comment] 2021-01-28 00:27
The only output that I get in the console is:
  I/flutter (14110): []
if I print the output of "MapLauncher.installedMaps".

Here is the output from flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 4.1.0)
[√] VS Code, 64-bit edition (version 1.20.1)
[√] Connected device (1 available)

• No issues found!

**Comment by mattermoran** [comment] 2021-01-28 00:30
Hmm, I wonder if it's because you running the beta. Let me try it

**Comment by mattermoran** [comment] 2021-01-28 00:45
So I just tried switching to the beta channel and running example project for this plugin and seems to be just fine. Something is definetely off but I can't yet see what. Have you tried any other android devices and see if the issue is still there? What is the android version on your pixel? I assume 11? My phone not yet updated to the latest android so I can't check if something has been changed in version 11.

**Comment by olsisaqe** [comment] 2021-01-29 22:51
I think things changed in version 11. More info: https://developer.android.com/about/versions/11/privacy/package-visibility

**Comment by mattermoran** [comment] 2021-01-30 02:59
@olsisaqe ha that makes sense. Looks like they did it similar plist file on ios. Thanks! Its hard to keep up with all the changes haha
I'll release a new version today

**Comment by mattermoran** [comment] 2021-01-30 14:46
@BasPhair @olsisaqe 
I added queries into AndroidManifest file could you check and see if works for you now?
You can install the version from github
```yaml
map_launcher:
    git: https://github.com/mattermoran/map_launcher
```

**Comment by BasPhair** [comment] 2021-01-30 18:25
Using the code you provided to add the dependency I now get the following error message:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':map_launcher:compileDebugKotlin'.

**Comment by mattermoran** [comment] 2021-01-31 05:46
sorry should've tried to compile first. needed gradle version bump for it to work. try now @BasPhair

**Comment by BasPhair** [comment] 2021-01-31 17:40
@mattermoran Appears to be all good!

**Comment by mattermoran** [comment] 2021-02-01 14:49
Awesome, closing

**Closed by mattermoran** 2021-02-01 14:49 UTC
